Update go example code
sous-chefs/golang pull request #95
Opened 2021-06-03 18:03 UTC by youshy

# Description

Fix test examples

## Issues Resolved

n/a

## Check List

- [X] All tests pass. See TESTING.md for details.
- [X] New functionality includes testing.

2021-06-03 18:05 UTC, Xorima commented on CHANGELOG.md
> +## 5.1.1 - *2021-06-03*
```suggestion
```

2021-06-03 18:05 UTC, Xorima submitted a review, later dismissed

2021-06-03 18:46 UTC, ramereth requested changes

2021-06-03 18:46 UTC, ramereth commented on CHANGELOG.md
> +
Can you please address this MDL error?

2021-06-03 18:50 UTC, Xorima commented on CHANGELOG.md
> +
```suggestion
```

2021-06-04 18:22 UTC, Xorima submitted a review, later dismissed

2021-06-04 18:36 UTC, Xorima approved these changes

2021-06-04 20:52 UTC, ramereth commented
@Xorima should we be concerned about the failure in `ubuntu-1804-src` ?

2021-06-04 21:13 UTC, Xorima approved these changes

2021-06-04 21:18 UTC, merged

2021-06-04 21:18 UTC, kitchen-porter commented
Released as: [5.2.0](https://github.com/sous-chefs/golang/releases/tag/5.2.0)