Fix unified_mode declaration
sous-chefs/golang pull request #99
Opened 2021-07-14 23:19 UTC by detjensrobert

Signed-off-by: Robert Detjens <detjensrobert@osuosl.org>

# Description

The previous PR (#92) did not properly set unified_mode for the default install resource.

This PR also bumps the pinned `ark` dependency to one with unified_mode enabled.

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2021-07-14 23:54 UTC, ramereth requested changes

2021-07-14 23:54 UTC, ramereth commented on metadata.rb
> +depends 'ark', '~> 6.0'
Can we please change it to the following so it's a bit more flexible for users?
```suggestion
depends 'ark', '>= 6.0'
```

2021-07-15 00:01 UTC, ramereth approved these changes

2021-07-15 00:10 UTC, merged

2021-07-15 00:10 UTC, kitchen-porter commented
Released as: [5.3.0](https://github.com/sous-chefs/golang/releases/tag/5.3.0)